name: Testing workflow Variables

on:
  workflow_dispatch

#Scope of this variable is workflow level
env:
  cloud: aws-cloud

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    #scope of the below variable is job level
    env:
      Greeting: Hello
    steps:
      - name: "Greeting step"
        run: echo "$Greeting $First_name is using $cloud"
        #scope of the below variable is step level
        env:
          First_name: Manoj
