name: Testing workflow Variables

on:
  workflow_dispatch

env:
  cloud: aws-cloud

jobs:
  greeting_job:
    runs-on: ubuntu:latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Manoj it is Sunday"
        run: echo "$Greeting $First_name is using $cloud
        env:
          First_name: Manoj
